/**
 * DeepSeek explanation service.
 * Called AFTER ML inference — only generates a text explanation.
 * ML results are authoritative and are NOT modified by DeepSeek.
 */
import axios, { AxiosError } from 'axios';
import { env } from '../config/env';
import { logger } from '../utils/logger';
import { AppError, ErrorCodes } from '../utils/errors';
import type { ExplanationRequest } from '../schemas/analysis.schema';

interface DeepSeekMessage {
  role: 'system' | 'user';
  content: string;
}

interface DeepSeekResponse {
  choices: Array<{
    message: { content: string };
  }>;
}

const SYSTEM_PROMPT = `You are an academic AI assistant helping explain brain tumor MRI analysis results 
generated by a trained machine learning model. You explain results in clear, accessible language.
You always include the disclaimer that this is an academic system and NOT a clinical diagnostic tool.
You never modify, question, or fabricate the ML model's prediction or confidence values.`;

function buildUserPrompt(req: ExplanationRequest): string {
  const segInfo = req.tumorPercentage != null
    ? `The segmentation model identified a tumor region covering approximately ${req.tumorPercentage.toFixed(1)}% of the image area (${req.tumorPixels?.toLocaleString() ?? 'N/A'} pixels).`
    : 'Segmentation data is not available.';

  return `
The trained VGG-16 brain tumor classifier analyzed an MRI scan and returned:
- Prediction: ${req.prediction === 'tumor' ? 'Tumor Detected' : 'No Tumor Detected'}
- Model Confidence: ${(req.confidence * 100).toFixed(1)}%
${segInfo}

Please write a brief, clear explanation of this result in 3-4 sentences for a student or researcher.
End with the academic disclaimer.
  `.trim();
}

export async function generateExplanation(req: ExplanationRequest): Promise<string> {
  if (!env.deepseekEnabled) {
    return '(AI explanation is unavailable: DEEPSEEK_API_KEY not configured.)';
  }

  const messages: DeepSeekMessage[] = [
    { role: 'system', content: SYSTEM_PROMPT },
    { role: 'user', content: buildUserPrompt(req) },
  ];

  try {
    const response = await axios.post<DeepSeekResponse>(
      `${env.deepseekBaseUrl}/v1/chat/completions`,
      {
        model: env.deepseekModel,
        messages,
        temperature: 0.3,
        max_tokens: 350,
      },
      {
        headers: {
          'Authorization': `Bearer ${env.deepseekApiKey}`,
          'Content-Type': 'application/json',
        },
        timeout: 30_000,
      }
    );

    const content = response.data.choices?.[0]?.message?.content ?? '';
    logger.info('DeepSeek explanation generated successfully');
    return content;

  } catch (err) {
    logger.error(`DeepSeek API error: ${err instanceof AxiosError ? err.message : String(err)}`);
    throw new AppError(
      ErrorCodes.DEEPSEEK_FAILED,
      'Failed to generate AI explanation. ML results are still valid.',
      502,
    );
  }
}
